//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 612
using System;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Collections.Generic;
using System.Text;
using Acme.MultiTenant.EFDAL;
using Acme.MultiTenant.EFDAL.EventArguments;
using System.Text.RegularExpressions;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;

namespace Acme.MultiTenant.EFDAL.Entity
{
	/// <summary>
	/// The 'TenantMaster' entity
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrate", "7.0.0")]
	[FieldNameConstants(typeof(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants))]
	[EntityMetadata("TenantMaster", false,true, true, true, "", true, false, false, "dbo")]
	[MetadataTypeAttribute(typeof(Acme.MultiTenant.EFDAL.Entity.Metadata.TenantMasterMetadata))]
	public partial class TenantMaster : BaseEntity, Acme.MultiTenant.EFDAL.IBusinessObject, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging, System.ICloneable, Acme.MultiTenant.EFDAL.IAuditable, Acme.MultiTenant.EFDAL.IAuditableSet, Acme.MultiTenant.EFDAL.ICreatable
	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'TenantMaster' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'DbPassword' property
			/// </summary>
			DbPassword,
			/// <summary>
			/// Field mapping for the 'DbUserName' property
			/// </summary>
			DbUserName,
			/// <summary>
			/// Field mapping for the 'TenantId' property
			/// </summary>
			[System.ComponentModel.DataAnnotations.Key]
			[System.ComponentModel.DataAnnotations.Editable(false)]
			TenantId,
			/// <summary>
			/// Field mapping for the 'TenantName' property
			/// </summary>
			TenantName,
			/// <summary>
			/// Field mapping for the 'CreatedBy' property
			/// </summary>
			CreatedBy,
			/// <summary>
			/// Field mapping for the 'CreatedDate' property
			/// </summary>
			CreatedDate,
			/// <summary>
			/// Field mapping for the 'ModifiedBy' property
			/// </summary>
			ModifiedBy,
			/// <summary>
			/// Field mapping for the 'ModifiedDate' property
			/// </summary>
			ModifiedDate,
		}
		#endregion

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the TenantMaster entity
		/// </summary>
		public TenantMaster()
		{
		}

		#endregion

		#region Properties

		/// <summary>
		/// The property that maps back to the database 'TenantMaster.DbPassword' field.
		/// </summary>
		/// <remarks>Field: [TenantMaster].[DbPassword], Field Length: 200, Not Nullable</remarks>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Always)]
		[System.ComponentModel.DataAnnotations.Display(Name = "DbPassword")]
		[System.ComponentModel.DataAnnotations.StringLength(200)]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string DbPassword
		{
			get { return _dbPassword; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbPassword))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "TenantMaster.DbPassword", GetMaxLength(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbPassword)));
				if (value == _dbPassword) return;
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>(value, "DbPassword");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_dbPassword = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("DbPassword"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'TenantMaster.DbUserName' field.
		/// </summary>
		/// <remarks>Field: [TenantMaster].[DbUserName], Field Length: 50, Not Nullable</remarks>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Always)]
		[System.ComponentModel.DataAnnotations.Display(Name = "DbUserName")]
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string DbUserName
		{
			get { return _dbUserName; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbUserName))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "TenantMaster.DbUserName", GetMaxLength(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbUserName)));
				if (value == _dbUserName) return;
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>(value, "DbUserName");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_dbUserName = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("DbUserName"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'TenantMaster.TenantId' field.
		/// </summary>
		/// <remarks>Field: [TenantMaster].[TenantId], Not Nullable, Primary Key, AutoNumber, Unique, Indexed</remarks>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Always)]
		[System.ComponentModel.DataAnnotations.Display(Name = "TenantId")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual int TenantId
		{
			get { return _tenantId; }
			protected internal set
			{
				if (value == _tenantId) return;
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<int>(value, "TenantId");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_tenantId = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("TenantId"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'TenantMaster.TenantName' field.
		/// </summary>
		/// <remarks>Field: [TenantMaster].[TenantName], Field Length: 50, Not Nullable</remarks>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Always)]
		[System.ComponentModel.DataAnnotations.Display(Name = "TenantName")]
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string TenantName
		{
			get { return _tenantName; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantName))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "TenantMaster.TenantName", GetMaxLength(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantName)));
				if (value == _tenantName) return;
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>(value, "TenantName");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_tenantName = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("TenantName"));
			}
		}

		/// <summary>
		/// The audit field for the 'Created By' parameter.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Never)]
		[System.Diagnostics.DebuggerNonUserCode()]
		[AuditCreatedBy]
		public virtual string CreatedBy
		{
			get { return _createdby; }
			protected internal set
			{
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>(value, "CreatedBy");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_createdby = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CreatedBy"));
			}
		}

		/// <summary />
		protected string _createdby;

		/// <summary>
		/// The audit field for the 'Created Date' parameter.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Never)]
		[System.Diagnostics.DebuggerNonUserCode()]
		[AuditCreatedDate]
		public virtual DateTime CreatedDate
		{
			get { return _createddate; }
			protected internal set
			{
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<DateTime>(value, "CreatedDate");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_createddate = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CreatedDate"));
			}
		}

		/// <summary />
		protected DateTime _createddate;

		/// <summary>
		/// The audit field for the 'Modified By' parameter.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Never)]
		[System.Diagnostics.DebuggerNonUserCode()]
		[AuditModifiedBy]
		public virtual string ModifiedBy
		{
			get { return _modifiedby; }
			protected internal set
			{
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>(value, "ModifiedBy");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_modifiedby = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ModifiedBy"));
			}
		}

		/// <summary />
		protected string _modifiedby;

		/// <summary>
		/// The audit field for the 'Modified Date' parameter.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Never)]
		[System.Diagnostics.DebuggerNonUserCode()]
		[AuditModifiedDate]
		public virtual DateTime ModifiedDate
		{
			get { return _modifieddate; }
			protected internal set
			{
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<DateTime>(value, "ModifiedDate");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_modifieddate = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ModifiedDate"));
			}
		}

		/// <summary />
		protected DateTime _modifieddate;

		/// <summary>
		/// The audit field for the 'Timestamp' parameter.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Never)]
		[System.Diagnostics.DebuggerNonUserCode()]
		[AuditTimestamp]
		public virtual byte[] Timestamp
		{
			get { return _timestamp; }
			protected internal set
			{
				var eventArg = new Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<byte[]>(value, "Timestamp");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_timestamp = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Timestamp"));
			}
		}

		/// <summary />
		protected byte[] _timestamp;

		#endregion

		#region Property Holders

		/// <summary />
		protected string _dbPassword;
		/// <summary>
		/// Occurs when the 'DbPassword' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>> DbPasswordChanging;

		/// <summary>
		/// Raises the OnDbPasswordChanging event.
		/// </summary>
		protected virtual void OnDbPasswordChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.DbPasswordChanging != null)
				this.DbPasswordChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'DbPassword' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<string>> DbPasswordChanged;

		/// <summary>
		/// Raises the OnDbPasswordChanged event.
		/// </summary>
		protected virtual void OnDbPasswordChanged(ChangedEventArgs<string> e)
		{
			if (this.DbPasswordChanged != null)
				this.DbPasswordChanged(this, e);
		}

		/// <summary />
		protected string _dbUserName;
		/// <summary>
		/// Occurs when the 'DbUserName' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>> DbUserNameChanging;

		/// <summary>
		/// Raises the OnDbUserNameChanging event.
		/// </summary>
		protected virtual void OnDbUserNameChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.DbUserNameChanging != null)
				this.DbUserNameChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'DbUserName' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<string>> DbUserNameChanged;

		/// <summary>
		/// Raises the OnDbUserNameChanged event.
		/// </summary>
		protected virtual void OnDbUserNameChanged(ChangedEventArgs<string> e)
		{
			if (this.DbUserNameChanged != null)
				this.DbUserNameChanged(this, e);
		}

		/// <summary />
		protected int _tenantId;
		/// <summary>
		/// Occurs when the 'TenantId' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<int>> TenantIdChanging;

		/// <summary>
		/// Raises the OnTenantIdChanging event.
		/// </summary>
		protected virtual void OnTenantIdChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<int> e)
		{
			if (this.TenantIdChanging != null)
				this.TenantIdChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'TenantId' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<int>> TenantIdChanged;

		/// <summary>
		/// Raises the OnTenantIdChanged event.
		/// </summary>
		protected virtual void OnTenantIdChanged(ChangedEventArgs<int> e)
		{
			if (this.TenantIdChanged != null)
				this.TenantIdChanged(this, e);
		}

		/// <summary />
		protected string _tenantName;
		/// <summary>
		/// Occurs when the 'TenantName' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>> TenantNameChanging;

		/// <summary>
		/// Raises the OnTenantNameChanging event.
		/// </summary>
		protected virtual void OnTenantNameChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.TenantNameChanging != null)
				this.TenantNameChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'TenantName' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<string>> TenantNameChanged;

		/// <summary>
		/// Raises the OnTenantNameChanged event.
		/// </summary>
		protected virtual void OnTenantNameChanged(ChangedEventArgs<string> e)
		{
			if (this.TenantNameChanged != null)
				this.TenantNameChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedBy' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>> CreatedByChanging;

		/// <summary>
		/// Raises the OnCreatedByChanging event.
		/// </summary>
		protected virtual void OnCreatedByChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.CreatedByChanging != null)
				this.CreatedByChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedBy' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<string>> CreatedByChanged;

		/// <summary>
		/// Raises the OnCreatedByChanged event.
		/// </summary>
		protected virtual void OnCreatedByChanged(ChangedEventArgs<string> e)
		{
			if (this.CreatedByChanged != null)
				this.CreatedByChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedDate' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<DateTime>> CreatedDateChanging;

		/// <summary>
		/// Raises the OnCreatedDateChanging event.
		/// </summary>
		protected virtual void OnCreatedDateChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<DateTime> e)
		{
			if (this.CreatedDateChanging != null)
				this.CreatedDateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedDate' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<DateTime>> CreatedDateChanged;

		/// <summary>
		/// Raises the OnCreatedDateChanged event.
		/// </summary>
		protected virtual void OnCreatedDateChanged(ChangedEventArgs<DateTime> e)
		{
			if (this.CreatedDateChanged != null)
				this.CreatedDateChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedBy' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string>> ModifiedByChanging;

		/// <summary>
		/// Raises the OnModifiedByChanging event.
		/// </summary>
		protected virtual void OnModifiedByChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.ModifiedByChanging != null)
				this.ModifiedByChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedBy' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<string>> ModifiedByChanged;

		/// <summary>
		/// Raises the OnModifiedByChanged event.
		/// </summary>
		protected virtual void OnModifiedByChanged(ChangedEventArgs<string> e)
		{
			if (this.ModifiedByChanged != null)
				this.ModifiedByChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedDate' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<DateTime>> ModifiedDateChanging;

		/// <summary>
		/// Raises the OnModifiedDateChanging event.
		/// </summary>
		protected virtual void OnModifiedDateChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<DateTime> e)
		{
			if (this.ModifiedDateChanging != null)
				this.ModifiedDateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedDate' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<DateTime>> ModifiedDateChanged;

		/// <summary>
		/// Raises the OnModifiedDateChanged event.
		/// </summary>
		protected virtual void OnModifiedDateChanged(ChangedEventArgs<DateTime> e)
		{
			if (this.ModifiedDateChanged != null)
				this.ModifiedDateChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'Timestamp' property value change is a pending.
		/// </summary>
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<byte[]>> TimestampChanging;

		/// <summary>
		/// Raises the OnTimestampChanging event.
		/// </summary>
		protected virtual void OnTimestampChanging(Acme.MultiTenant.EFDAL.EventArguments.ChangingEventArgs<byte[]> e)
		{
			if (this.TimestampChanging != null)
				this.TimestampChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Timestamp' property value has changed.
		/// </summary>
		public event EventHandler<ChangedEventArgs<byte[]>> TimestampChanged;

		/// <summary>
		/// Raises the OnTimestampChanged event.
		/// </summary>
		protected virtual void OnTimestampChanged(ChangedEventArgs<byte[]> e)
		{
			if (this.TimestampChanged != null)
				this.TimestampChanged(this, e);
		}


		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants field)
		{
			switch (field)
			{
				case Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbPassword:
					return 200;
				case Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbUserName:
					return 50;
				case Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantId:
					return 0; //Type=Int
				case Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantName:
					return 50;
			}
			return 0;
		}

		int Acme.MultiTenant.EFDAL.IReadOnlyBusinessObject.GetMaxLength(Enum field)
		{
			return GetMaxLength((Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants)field);
		}

		#endregion

		#region GetFieldNameConstants

		System.Type Acme.MultiTenant.EFDAL.IReadOnlyBusinessObject.GetFieldNameConstants()
		{
			return typeof(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants);
		}

		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants field)
		{
			if (field.GetType() != typeof(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants'.");

			switch ((Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants)field)
			{
				case Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbPassword: return typeof(string);
				case Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbUserName: return typeof(string);
				case Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantId: return typeof(int);
				case Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantName: return typeof(string);
			}
			return null;
		}

		System.Type Acme.MultiTenant.EFDAL.IReadOnlyBusinessObject.GetFieldType(Enum field)
		{
			if (field.GetType() != typeof(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants'.");

			return GetFieldType((Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants)field);
		}

		#endregion

		#region Get/Set Value

		object Acme.MultiTenant.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field)
		{
			return ((Acme.MultiTenant.EFDAL.IReadOnlyBusinessObject)this).GetValue(field, null);
		}

		object Acme.MultiTenant.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field, object defaultValue)
		{
			if (field.GetType() != typeof(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants'.");
			return this.GetValue((Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants)field, defaultValue);
		}

		void Acme.MultiTenant.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue)
		{
			if (field.GetType() != typeof(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants'.");
			this.SetValue((Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants)field, newValue);
		}

		void Acme.MultiTenant.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue, bool fixLength)
		{
			if (field.GetType() != typeof(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants'.");
			this.SetValue((Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants)field, newValue, fixLength);
		}

		#endregion

		#region PrimaryKey

		/// <summary>
		/// Generic primary key for this object
		/// </summary>
		Acme.MultiTenant.EFDAL.IPrimaryKey Acme.MultiTenant.EFDAL.IReadOnlyBusinessObject.PrimaryKey
		{
			get { return new PrimaryKey(Util.HashPK("TenantMaster", this.TenantId)); }
		}

		#endregion

		#region Clone

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public virtual object Clone()
		{
			return Acme.MultiTenant.EFDAL.Entity.TenantMaster.Clone(this);
		}

		/// <summary>
		/// Creates a shallow copy of this object with defined, default values and new PK
		/// </summary>
		public virtual object CloneAsNew()
		{
			var item = Acme.MultiTenant.EFDAL.Entity.TenantMaster.Clone(this);
			item._tenantId = 0;
			return item;
		}

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public static TenantMaster Clone(Acme.MultiTenant.EFDAL.Entity.TenantMaster item)
		{
			var newItem = new TenantMaster();
			newItem.DbPassword = item.DbPassword;
			newItem.DbUserName = item.DbUserName;
			newItem.TenantId = item.TenantId;
			newItem.TenantName = item.TenantName;
			newItem.CreatedDate = item.CreatedDate;
			newItem.CreatedBy = item.CreatedBy;
			newItem.ModifiedDate = item.ModifiedDate;
			newItem.ModifiedBy = item.ModifiedBy;
			return newItem;
		}

		#endregion

		#region GetValue

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants field)
		{
			return GetValue(field, null);
		}

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants field, object defaultValue)
		{
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbPassword)
				return this.DbPassword;
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbUserName)
				return this.DbUserName;
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantId)
				return this.TenantId;
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantName)
				return this.TenantName;
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.CreatedBy)
				return ((this.CreatedBy == null) ? defaultValue : this.CreatedBy);
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.CreatedDate)
				return ((this.CreatedDate == null) ? defaultValue : this.CreatedDate);
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.ModifiedBy)
				return ((this.ModifiedBy == null) ? defaultValue : this.ModifiedBy);
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.ModifiedDate)
				return ((this.ModifiedDate == null) ? defaultValue : this.ModifiedDate);
			throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region SetValue

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		public virtual void SetValue(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants field, object newValue)
		{
			SetValue(field, newValue, false);
		}

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		/// <param name="fixLength">Determines if the length should be truncated if too long. When false, an error will be raised if data is too large to be assigned to the field.</param>
		public virtual void SetValue(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants field, object newValue, bool fixLength)
		{
			if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbPassword)
			{
				this.DbPassword = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.DbUserName)
			{
				this.DbUserName = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantId)
			{
				throw new Exception("Field '" + field.ToString() + "' is a primary key and cannot be set!");
			}
			else if (field == Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants.TenantName)
			{
				this.TenantName = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else
				throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region Navigation Properties

		/// <summary>
		/// The navigation definition for walking TenantMaster->UserAccount
		/// </summary>
		public virtual ICollection<Acme.MultiTenant.EFDAL.Entity.UserAccount> UserAccountList
		{
			get; protected internal set;
		}

		#endregion

		#region GetDatabaseFieldName

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants field)
		{
			return GetDatabaseFieldName(field.ToString());
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "DbPassword": return "DbPassword";
				case "DbUserName": return "DbUserName";
				case "TenantId": return "TenantId";
				case "TenantName": return "TenantName";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "Timestamp": return "Timestamp";
			}
			return string.Empty;
		}

		#endregion

		#region Auditing
		string Acme.MultiTenant.EFDAL.IAuditableSet.CreatedBy
		{
			set { this.CreatedBy = value; }
		}

		string Acme.MultiTenant.EFDAL.IAuditableSet.ModifiedBy
		{
			set { this.ModifiedBy = value; }
		}

		string Acme.MultiTenant.EFDAL.IAuditable.CreatedBy
		{
			get { return this.CreatedBy; }
		}

		System.DateTime? Acme.MultiTenant.EFDAL.IAuditable.CreatedDate
		{
			get { return this.CreatedDate; }
		}

		bool Acme.MultiTenant.EFDAL.IAuditable.IsCreateAuditImplemented
		{
			get { return true; }
		}

		bool Acme.MultiTenant.EFDAL.IAuditable.IsModifyAuditImplemented
		{
			get { return true; }
		}

		bool Acme.MultiTenant.EFDAL.IAuditable.IsTimestampAuditImplemented
		{
			get { return true; }
		}

		string Acme.MultiTenant.EFDAL.IAuditable.ModifiedBy
		{
			get { return this.ModifiedBy; }
		}

		System.DateTime? Acme.MultiTenant.EFDAL.IAuditable.ModifiedDate
		{
			get { return this.ModifiedDate; }
		}

		byte[] Acme.MultiTenant.EFDAL.IAuditable.TimeStamp
		{
			get { return this.Timestamp; }
		}

		System.DateTime Acme.MultiTenant.EFDAL.IAuditableSet.CreatedDate
		{
			set { this.CreatedDate = value; }
		}

		System.DateTime Acme.MultiTenant.EFDAL.IAuditableSet.ModifiedDate
		{
			set { this.ModifiedDate = value; }
		}

		#endregion

		#region Equals
		/// <summary>
		/// Compares two objects of 'TenantMaster' type and determines if all properties match
		/// </summary>
		/// <returns>True if all properties match, false otherwise</returns>
		public override bool Equals(object obj)
		{
			var other = obj as Acme.MultiTenant.EFDAL.Entity.TenantMaster;
			if (other == null) return false;
			return (
				other.DbPassword == this.DbPassword &&
				other.DbUserName == this.DbUserName &&
				other.TenantId == this.TenantId &&
				other.TenantName == this.TenantName
				);
		}

		/// <summary>
		/// Serves as a hash function for this type.
		/// </summary>
		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		#endregion

	}
}

#region Metadata Class

namespace Acme.MultiTenant.EFDAL.Entity.Metadata
{
	/// <summary>
	/// Metadata class for the 'TenantMaster' entity
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrate", "7.0.0")]
	public partial class TenantMasterMetadata : Acme.MultiTenant.EFDAL.IMetadata
	{
		#region Properties

		/// <summary>
		/// Metadata information for the 'DbPassword' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'DbPassword' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(200, ErrorMessage = "The property 'DbPassword' has a maximum length of 200")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "DbPassword", AutoGenerateField = true)]
		public object DbPassword;

		/// <summary>
		/// Metadata information for the 'DbUserName' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'DbUserName' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(50, ErrorMessage = "The property 'DbUserName' has a maximum length of 50")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "DbUserName", AutoGenerateField = true)]
		public object DbUserName;

		/// <summary>
		/// Metadata information for the 'TenantId' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'TenantId' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.ComponentModel.DataAnnotations.Editable(false)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "TenantId", AutoGenerateField = true)]
		public object TenantId;

		/// <summary>
		/// Metadata information for the 'TenantName' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'TenantName' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(50, ErrorMessage = "The property 'TenantName' has a maximum length of 50")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "TenantName", AutoGenerateField = true)]
		public object TenantName;

		/// <summary>
		/// Metadata information for the 'CreatedBy' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'CreatedBy' has a maximum length of 100")]
		[System.ComponentModel.DataAnnotations.Editable(false)]
		public object CreatedBy;

		/// <summary>
		/// Metadata information for the 'CreatedDate' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Editable(false)]
		public object CreatedDate;

		/// <summary>
		/// Metadata information for the 'ModifiedBy' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'ModifiedBy' has a maximum length of 100")]
		[System.ComponentModel.DataAnnotations.Editable(false)]
		public object ModifiedBy;

		/// <summary>
		/// Metadata information for the 'ModifiedDate' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Editable(false)]
		public object ModifiedDate;

		/// <summary>
		/// Metadata information for the 'Timestamp' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Timestamp()]
		[System.ComponentModel.DataAnnotations.ConcurrencyCheck()]
		[System.ComponentModel.DataAnnotations.Editable(false)]
		public object Timestamp;

		#endregion

		#region Methods
		/// <summary />
		public virtual string GetTableName()
		{
			return "TenantMaster";
		}

		/// <summary>
		/// Gets a list of all object fields with alias/code facade applied excluding inheritance.
		/// </summary>
		public virtual List<string> GetFields()
		{
			var retval = new List<string>();
			retval.Add("DbPassword");
			retval.Add("DbUserName");
			retval.Add("TenantId");
			retval.Add("TenantName");
			return retval;
		}

		/// <summary>
		/// Returns the type of the parent object if one exists.
		/// </summary>
		public virtual System.Type InheritsFrom()
		{
			return null;
		}

		/// <summary>
		/// Returns the database schema name.
		/// </summary>
		public virtual string Schema()
		{
			return "dbo";
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		public virtual string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "DbPassword": return "DbPassword";
				case "DbUserName": return "DbUserName";
				case "TenantId": return "TenantId";
				case "TenantName": return "TenantName";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "Timestamp": return "Timestamp";
			}
			return string.Empty;
		}

		#endregion

	}

}

#endregion

#pragma warning restore 612

