//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 0168
#pragma warning disable 0108
using System;
using System.Linq;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using Acme.MultiTenant.EFDAL.Entity;

namespace Acme.MultiTenant.EFDAL
{
	#region StaticDataConstants Enumeration for 'ProjectType' entity
	/// <summary>
	/// Enumeration to define static data items and their ids 'ProjectType' table.
	/// </summary>
	public enum ProjectTypeConstants
	{
		/// <summary>
		/// Enumeration for the 'CSharp' item
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Name = "CSharp")]
		CSharp = 1,
		/// <summary>
		/// Enumeration for the 'Java' item
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Name = "Java")]
		Java = 2,
		/// <summary>
		/// Enumeration for the 'Python' item
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Name = "Python")]
		Python = 3,
	}
	#endregion

	#region Entity Context

	/// <summary />
	[System.CodeDom.Compiler.GeneratedCode("nHydrate", "7.0.0")]
	public partial interface IMultiTenantEntities : System.IDisposable
	{
		/// <summary />
		int SaveChanges();

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.Project> Project { get ; }

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.ProjectFile> ProjectFile { get ; }

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.ProjectType> ProjectType { get ; }

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.TenantMaster> TenantMaster { get ; }

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.UserAccount> UserAccount { get ; }

		/// <summary />
		Acme.MultiTenant.EFDAL.IBusinessObject AddItem(Acme.MultiTenant.EFDAL.IBusinessObject entity);

		/// <summary />
		void RemoveItem(Acme.MultiTenant.EFDAL.IBusinessObject entity);

		/// <summary />
		void ReloadItem(BaseEntity entity);

		/// <summary />
		ContextStartup ContextStartup { get; }

		/// <summary />
		System.Guid InstanceKey { get; }
	}

	#endregion

}

#pragma warning restore 0168
#pragma warning restore 0108
