//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 612
using System;
using System.Linq;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Acme.MultiTenant.EFDAL.Entity;
using System.Data.SqlClient;
using System.Configuration;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace Acme.MultiTenant.EFDAL
{
	#region EntityMappingConstants Enumeration

	/// <summary>
	/// A map for all entity types in this library
	/// </summary>
	public enum EntityMappingConstants
	{
		/// <summary>
		/// A mapping for the the Project entity
		/// </summary>
		Project,
		/// <summary>
		/// A mapping for the the ProjectFile entity
		/// </summary>
		ProjectFile,
		/// <summary>
		/// A mapping for the the ProjectType entity
		/// </summary>
		ProjectType,
		/// <summary>
		/// A mapping for the the TenantMaster entity
		/// </summary>
		TenantMaster,
		/// <summary>
		/// A mapping for the the UserAccount entity
		/// </summary>
		UserAccount,
	}

	#endregion

	#region Entity Context

	/// <summary>
	/// The entity context for the defined model schema
	/// </summary>
	public partial class MultiTenantEntities : Microsoft.EntityFrameworkCore.DbContext, Acme.MultiTenant.EFDAL.IMultiTenantEntities, IContext
	{
		/// <summary />
		public static Action<string> QueryLogger { get; set; }

		/// <summary>
		/// A unique key for this object instance
		/// </summary>
		public Guid InstanceKey { get; private set; }

		/// <summary>
		/// The audit modifier used to mark database edits
		/// </summary>
		protected ContextStartup _contextStartup = new ContextStartup(null);

		private static object _seqCacheLock = new object();

		private const string _version = "0.0.0.0.1";
		private const string _modelKey = "7806e9fd-a366-4753-b122-4f7c0a05b85a";
		protected string _connectionString = null;

		/// <summary />
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.EntityListEventArgs> BeforeSaveModifiedEntity;
		/// <summary />
		protected virtual void OnBeforeSaveModifiedEntity(Acme.MultiTenant.EFDAL.EventArguments.EntityListEventArgs e)
		{
			if(this.BeforeSaveModifiedEntity != null)
			{
				this.BeforeSaveModifiedEntity(this, e);
			}
		}

		/// <summary />
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.EntityListEventArgs> BeforeSaveAddedEntity;
		/// <summary />
		protected virtual void OnBeforeSaveAddedEntity(Acme.MultiTenant.EFDAL.EventArguments.EntityListEventArgs e)
		{
			if(this.BeforeSaveAddedEntity != null)
			{
				this.BeforeSaveAddedEntity(this, e);
			}
		}

		/// <summary />
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.EntityListEventArgs> AfterSaveModifiedEntity;
		/// <summary />
		protected virtual void OnAfterSaveModifiedEntity(Acme.MultiTenant.EFDAL.EventArguments.EntityListEventArgs e)
		{
			if(this.AfterSaveModifiedEntity != null)
			{
				this.AfterSaveModifiedEntity(this, e);
			}
		}

		/// <summary />
		public event EventHandler<Acme.MultiTenant.EFDAL.EventArguments.EntityListEventArgs> AfterSaveAddedEntity;
		/// <summary />
		protected virtual void OnAfterSaveAddedEntity(Acme.MultiTenant.EFDAL.EventArguments.EntityListEventArgs e)
		{
			if(this.AfterSaveAddedEntity != null)
			{
				this.AfterSaveAddedEntity(this, e);
			}
		}

		#region Constructors

		/// <summary>
	/// Initializes a new MultiTenantEntities object using the connection string found in the 'MultiTenantEntities' section of the application configuration file.
		/// </summary>
		public MultiTenantEntities() :
			base()
		{
			_connectionString = ConfigurationManager.ConnectionStrings["MultiTenantEntities"]?.ConnectionString;
			InstanceKey = Guid.NewGuid();
			_contextStartup = new ContextStartup(null, true);
			this.CommandTimeout = _contextStartup.CommandTimeout;
			this.OnContextCreated();
		}

		/// <summary>
	/// Initialize a new MultiTenantEntities object with an audit modifier.
		/// </summary>
		public MultiTenantEntities(ContextStartup contextStartup) :
				base()
		{
			_connectionString = ConfigurationManager.ConnectionStrings["MultiTenantEntities"]?.ConnectionString;
			InstanceKey = Guid.NewGuid();
			_contextStartup = contextStartup;
			this.CommandTimeout = _contextStartup.CommandTimeout;
			this.OnContextCreated();
		}

		/// <summary>
	/// Initialize a new MultiTenantEntities object with an audit modifier.
		/// </summary>
		public MultiTenantEntities(ContextStartup contextStartup, string connectionString) :
				base()
		{
			_connectionString = connectionString;
			InstanceKey = Guid.NewGuid();
			_contextStartup = contextStartup;
			this.CommandTimeout = _contextStartup.CommandTimeout;
			this.OnContextCreated();
		}

		/// <summary>
	/// Initialize a new MultiTenantEntities object with an audit modifier.
		/// </summary>
		public MultiTenantEntities(string connectionString) :
				base()
		{
			_connectionString = connectionString;
			InstanceKey = Guid.NewGuid();
			_contextStartup = new ContextStartup(null, true);
			this.CommandTimeout = _contextStartup.CommandTimeout;
			this.OnContextCreated();
		}

		#endregion

		partial void OnContextCreated();
		partial void OnBeforeSaveChanges(ref bool cancel);
		partial void OnAfterSaveChanges();
		partial void OnModelCreated(ModelBuilder modelBuilder);

		/// <summary>
		/// Model creation event
		/// </summary>
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			#region Map Tables
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().ToTable("__vw_tenant_Project");
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>().ToTable("__vw_tenant_ProjectFile");
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectType>().ToTable("ProjectType");
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().ToTable("TenantMaster");
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().ToTable("UserAccount");
			#endregion

			#region Setup Fields

			//Field setup for Project entity
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().Property(d => d.Name).IsRequired(true).HasMaxLength(50);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().Property(d => d.ProjectId).IsRequired(true).ValueGeneratedOnAdd();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().Ignore(d => d.ProjectTypeValue);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().Property(d => d.ProjectTypeId).IsRequired(true);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().Property(d => d.CreatedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().Property(d => d.ModifiedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().Property(d => d.Timestamp).HasMaxLength(8).IsRowVersion();

			//Field setup for ProjectFile entity
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>().Property(d => d.FileName).IsRequired(true).HasMaxLength(450);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>().Property(d => d.ProjectFileId).IsRequired(true).ValueGeneratedOnAdd();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>().Property(d => d.ProjectId).IsRequired(true);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>().Property(d => d.CreatedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>().Property(d => d.ModifiedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>().Property(d => d.Timestamp).HasMaxLength(8).IsRowVersion();

			//Field setup for ProjectType entity
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectType>().Property(d => d.Name).IsRequired(true).HasMaxLength(50);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectType>().Ignore(d => d.ProjectTypeValue);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectType>().Property(d => d.ProjectTypeId).IsRequired(true).ValueGeneratedOnAdd();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectType>().Property(d => d.CreatedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectType>().Property(d => d.ModifiedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectType>().Property(d => d.Timestamp).HasMaxLength(8).IsRowVersion();

			//Field setup for TenantMaster entity
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().Property(d => d.DbPassword).IsRequired(true).HasMaxLength(200);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().Property(d => d.DbUserName).IsRequired(true).HasMaxLength(50);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().Property(d => d.TenantId).IsRequired(true).ValueGeneratedOnAdd();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().Property(d => d.TenantName).IsRequired(true).HasMaxLength(50);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().Property(d => d.CreatedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().Property(d => d.ModifiedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().Property(d => d.Timestamp).HasMaxLength(8).IsRowVersion();

			//Field setup for UserAccount entity
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().Property(d => d.PasswordHash).IsRequired(true).HasMaxLength(50);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().Property(d => d.TenantId).IsRequired(true);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().Property(d => d.UserId).IsRequired(true).ValueGeneratedOnAdd();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().Property(d => d.UserName).IsRequired(true).HasMaxLength(50);
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().Property(d => d.CreatedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().Property(d => d.ModifiedDate).IsRequired();
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().Property(d => d.Timestamp).HasMaxLength(8).IsRowVersion();

			#endregion

			#region Ignore Enum Properties

			modelBuilder.Entity<Project>().Ignore(t => t.ProjectTypeValue);
			modelBuilder.Entity<ProjectType>().Ignore(t => t.ProjectTypeValue);

			#endregion

			#region Primary Keys

			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>().HasKey(x => new { x.ProjectId });
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>().HasKey(x => new { x.ProjectFileId });
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectType>().HasKey(x => new { x.ProjectTypeId });
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.TenantMaster>().HasKey(x => new { x.TenantId });
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>().HasKey(x => new { x.UserId });

			#endregion

			#region Relations

			//Relation [Project] -> [ProjectFile] (Multiplicity 1:N)
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.ProjectFile>()
							.HasOne(a => a.Project)
							.WithMany(b => b.ProjectFileList)
							.IsRequired(true)
							.HasPrincipalKey(q => new { q.ProjectId })
							.HasForeignKey(u => new { u.ProjectId })
							.HasConstraintName("FK__PROJECTFILE_PROJECT")
							.OnDelete(DeleteBehavior.Restrict);

			//Relation [ProjectType] -> [Project] (Multiplicity 1:N)
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.Project>()
							.HasOne(a => a.ProjectType)
							.WithMany(b => b.ProjectList)
							.IsRequired(true)
							.HasPrincipalKey(q => new { q.ProjectTypeId })
							.HasForeignKey(u => new { u.ProjectTypeId })
							.HasConstraintName("FK__PROJECT_PROJECTTYPE")
							.OnDelete(DeleteBehavior.Restrict);

			//Relation [TenantMaster] -> [UserAccount] (Multiplicity 1:N)
			modelBuilder.Entity<Acme.MultiTenant.EFDAL.Entity.UserAccount>()
							.HasOne(a => a.TenantMaster)
							.WithMany(b => b.UserAccountList)
							.IsRequired(true)
							.HasPrincipalKey(q => new { q.TenantId })
							.HasForeignKey(u => new { u.TenantId })
							.HasConstraintName("FK__USERACCOUNT_TENANTMASTER")
							.OnDelete(DeleteBehavior.Restrict);

			#endregion

			#region Stored Procedures


			#endregion

			// Override this event in the partial class to add any custom model changes or validation
			this.OnModelCreated(modelBuilder);

		}

		/// <summary>
		/// Persists all updates to the data source and resets change tracking in the object context.
		/// </summary>
		/// <returns>The number of objects in an System.Data.Entity.EntityState.Added, System.Data.Entity.EntityState.Modified, or System.Data.Entity.EntityState.Deleted state when System.Data.Objects.ObjectContext.SaveChanges() was called.</returns>
		public override int SaveChanges()
		{
			var cancel = false;
			OnBeforeSaveChanges(ref cancel);
			if (cancel) return 0;

			var markedTime = System.DateTime.Now;

			//Get the added list
			var addedList = this.ChangeTracker.Entries().Where(x => x.State == EntityState.Added);
			//Process added list
			foreach (var item in addedList)
			{
				var entity = item.Entity as IAuditable;
				if (entity != null)
				{
					var audit = entity as IAuditableSet;
					if (entity.IsModifyAuditImplemented && entity.ModifiedBy != this.ContextStartup.Modifier)
					{
						if (audit != null) audit.CreatedBy = this.ContextStartup.Modifier;
						if (audit != null) audit.ModifiedBy = this.ContextStartup.Modifier;
					}
					audit.CreatedDate = markedTime;
					audit.ModifiedDate = markedTime;
				}
			}
			this.OnBeforeSaveAddedEntity(new EventArguments.EntityListEventArgs { List = addedList });

			//Process modified list
			var modifiedList = this.ChangeTracker.Entries().Where(x => x.State == EntityState.Modified);
			foreach (var item in modifiedList)
			{
				var entity = item.Entity as IAuditable;
				if (entity != null)
				{
					var audit = entity as IAuditableSet;
					if (entity.IsModifyAuditImplemented && entity.ModifiedBy != this.ContextStartup.Modifier)
					{
						if (audit != null) audit.ModifiedBy = this.ContextStartup.Modifier;
					}
					audit.ModifiedDate = markedTime;
				}
			}
			this.OnBeforeSaveModifiedEntity(new EventArguments.EntityListEventArgs { List = modifiedList });

			var retval = 0;
			Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction customTrans = null;
			try
			{
				_paramList.Clear();
				if (base.Database.CurrentTransaction == null)
					customTrans = base.Database.BeginTransaction();
				retval += base.SaveChanges();
				if (customTrans != null)
					customTrans.Commit();
			}
			catch
			{
				throw;
			}
			finally
			{
				if (customTrans != null)
					customTrans.Dispose();
			}
			this.OnAfterSaveAddedEntity(new EventArguments.EntityListEventArgs { List = addedList });
			this.OnAfterSaveModifiedEntity(new EventArguments.EntityListEventArgs { List = modifiedList });
			OnAfterSaveChanges();
			return retval;
		}

		#region Entity Sets

		/// <summary>
		/// Entity set for Project
		/// </summary>
		public virtual DbSet<Acme.MultiTenant.EFDAL.Entity.Project> Project { get; set; }

		/// <summary>
		/// Entity set for ProjectFile
		/// </summary>
		public virtual DbSet<Acme.MultiTenant.EFDAL.Entity.ProjectFile> ProjectFile { get; set; }

		/// <summary>
		/// Entity set for ProjectType
		/// </summary>
		public virtual DbSet<Acme.MultiTenant.EFDAL.Entity.ProjectType> ProjectType { get; set; }

		/// <summary>
		/// Entity set for TenantMaster
		/// </summary>
		public virtual DbSet<Acme.MultiTenant.EFDAL.Entity.TenantMaster> TenantMaster { get; set; }

		/// <summary>
		/// Entity set for UserAccount
		/// </summary>
		public virtual DbSet<Acme.MultiTenant.EFDAL.Entity.UserAccount> UserAccount { get; set; }

		#endregion

		/// <summary>
		/// The global settings of this context
		/// </summary>
		public virtual ContextStartup ContextStartup
		{
			get { return _contextStartup; }
		}

		/// <summary>
		/// Determines the version of the model that created this library.
		/// </summary>
		public virtual string Version
		{
			get { return _version; }
		}

		/// <summary>
		/// Determines the key of the model that created this library.
		/// </summary>
		public virtual string ModelKey
		{
			get { return _modelKey; }
		}

		#region AddItem Methods

        public override EntityEntry Add( object entity)
        {
            //No model validation. You should use the AddItem method.
            return base.Add(entity);
        }

        public override EntityEntry<TEntity> Add<TEntity>( TEntity entity)
        {
            //No model validation. You should use the AddItem method.
            return base.Add(entity);
        }

        public override void AddRange(IEnumerable<object> entities)
        {
            if (entities == null) return;
            //This will enforce model validation.
            foreach (var item in entities)
            {
                var entity = item as IBusinessObject;
                if (entity == null)
                    throw new Exception("Unknown entity type");
                this.AddItem(entity);
            }
        }

        public override void AddRange(params object[] entities)
        {
            this.AddRange(entities?.AsEnumerable());
        }

        public virtual void AddRange(IEnumerable<IBusinessObject> entities)
        {
            this.AddRange(entities?.AsEnumerable<object>());
        }

		/// <summary>
		/// Adds an entity of to the object context
		/// </summary>
		/// <param name="entity">The entity to add</param>
		public virtual Acme.MultiTenant.EFDAL.IBusinessObject AddItem(Acme.MultiTenant.EFDAL.IBusinessObject entity)
		{
			if (entity == null) throw new NullReferenceException();
			var audit = entity as Acme.MultiTenant.EFDAL.IAuditableSet;
			if (audit != null)
			{
				audit.CreatedBy = _contextStartup.Modifier;
				audit.ModifiedBy = _contextStartup.Modifier;
			}
			if (false) { }
			else if (entity is Acme.MultiTenant.EFDAL.Entity.Project)
			{
				this.Add(entity);
			}
			else if (entity is Acme.MultiTenant.EFDAL.Entity.ProjectFile)
			{
				this.Add(entity);
			}
			else if (entity is Acme.MultiTenant.EFDAL.Entity.TenantMaster)
			{
				this.Add(entity);
			}
			else if (entity is Acme.MultiTenant.EFDAL.Entity.UserAccount)
			{
				this.Add(entity);
			}
			else
			{
				//If not an entity then throw exception
				throw new Exception("Unknown entity type");
			}
			return entity;
		}

		#endregion

		#region RemoveItem Methods

        public override EntityEntry Remove( object entity)
        {
            //No model validation. You should use the RemoveItem method.
            return base.Remove(entity);
        }

        public override EntityEntry<TEntity> Remove<TEntity>( TEntity entity)
        {
            //No model validation. You should use the RemoveItem method.
            return base.Remove(entity);
        }

        public override void RemoveRange(IEnumerable<object> entities)
        {
            if (entities == null) return;
            foreach (var item in entities)
            {
                var entity = item as IBusinessObject;
                if (entity == null)
                    throw new Exception("Unknown entity type");
                this.RemoveItem(entity);
            }
        }

        public override void RemoveRange(params object[] entities)
        {
            this.RemoveRange(entities?.AsEnumerable());
        }

        public virtual void RemoveRange(IEnumerable<IBusinessObject> entities)
        {
            this.RemoveRange(entities?.AsEnumerable<object>());
        }

		/// <summary>
		/// Deletes an entity from the context
		/// </summary>
		/// <param name="entity">The entity to delete</param>
		public virtual void RemoveItem(IBusinessObject entity)
		{
			if (entity == null) return;
			else this.Remove(entity);
		}

		#endregion

		#region Connection String

		/// <summary>
		/// Returns the connection string used for this context object
		/// </summary>
		public string ConnectionString
		{
			get
			{
				try
				{
					if (this.Database.GetDbConnection() != null && !string.IsNullOrEmpty(this.Database.GetDbConnection().ConnectionString))
					{
						return Util.StripEFCS2Normal(this.Database.GetDbConnection().ConnectionString);
					}
					else
					{
						return null;
					}
				}
				catch (Exception)
				{
					return null;
				}
			}
		}

		#endregion

		#region IMultiTenant Members

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.Project> Acme.MultiTenant.EFDAL.IMultiTenantEntities.Project
		{
			get { return this.Project.AsQueryable(); }
		}

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.ProjectFile> Acme.MultiTenant.EFDAL.IMultiTenantEntities.ProjectFile
		{
			get { return this.ProjectFile.AsQueryable(); }
		}

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.ProjectType> Acme.MultiTenant.EFDAL.IMultiTenantEntities.ProjectType
		{
			get { return this.ProjectType.AsQueryable(); }
		}

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.TenantMaster> Acme.MultiTenant.EFDAL.IMultiTenantEntities.TenantMaster
		{
			get { return this.TenantMaster.AsQueryable(); }
		}

		/// <summary />
		IQueryable<Acme.MultiTenant.EFDAL.Entity.UserAccount> Acme.MultiTenant.EFDAL.IMultiTenantEntities.UserAccount
		{
			get { return this.UserAccount.AsQueryable(); }
		}

		/// <summary />
		protected List<string> _paramList = new List<string>();
		#endregion

		#region IContext Interface

		Enum IContext.GetEntityFromField(Enum field)
		{
			return GetEntityFromField(field);
		}

		object IContext.GetMetaData(Enum entity)
		{
			return GetMetaData((EntityMappingConstants)entity);
		}

		System.Type IContext.GetFieldType(Enum field)
		{
			return this.GetFieldType(field);
		}

		#endregion

		#region GetEntityFromField

		/// <summary>
		/// Determines the entity from one of its fields
		/// </summary>
		public static EntityMappingConstants GetEntityFromField(Enum field)
		{
			if (field is Acme.MultiTenant.EFDAL.Entity.Project.FieldNameConstants) return Acme.MultiTenant.EFDAL.EntityMappingConstants.Project;
			if (field is Acme.MultiTenant.EFDAL.Entity.ProjectFile.FieldNameConstants) return Acme.MultiTenant.EFDAL.EntityMappingConstants.ProjectFile;
			if (field is Acme.MultiTenant.EFDAL.Entity.ProjectType.FieldNameConstants) return Acme.MultiTenant.EFDAL.EntityMappingConstants.ProjectType;
			if (field is Acme.MultiTenant.EFDAL.Entity.TenantMaster.FieldNameConstants) return Acme.MultiTenant.EFDAL.EntityMappingConstants.TenantMaster;
			if (field is Acme.MultiTenant.EFDAL.Entity.UserAccount.FieldNameConstants) return Acme.MultiTenant.EFDAL.EntityMappingConstants.UserAccount;
			throw new Exception("Unknown field type!");
		}

		#endregion

		#region GetMetaData

		/// <summary>
		/// Gets the meta data object for an entity
		/// </summary>
		public static Acme.MultiTenant.EFDAL.IMetadata GetMetaData(Acme.MultiTenant.EFDAL.EntityMappingConstants table)
		{
			switch (table)
			{
				case Acme.MultiTenant.EFDAL.EntityMappingConstants.Project: return new Acme.MultiTenant.EFDAL.Entity.Metadata.ProjectMetadata();
				case Acme.MultiTenant.EFDAL.EntityMappingConstants.ProjectFile: return new Acme.MultiTenant.EFDAL.Entity.Metadata.ProjectFileMetadata();
				case Acme.MultiTenant.EFDAL.EntityMappingConstants.ProjectType: return new Acme.MultiTenant.EFDAL.Entity.Metadata.ProjectTypeMetadata();
				case Acme.MultiTenant.EFDAL.EntityMappingConstants.TenantMaster: return new Acme.MultiTenant.EFDAL.Entity.Metadata.TenantMasterMetadata();
				case Acme.MultiTenant.EFDAL.EntityMappingConstants.UserAccount: return new Acme.MultiTenant.EFDAL.Entity.Metadata.UserAccountMetadata();
			}
			throw new Exception("Entity not found!");
		}

		/// <summary />
		public static string GetTableName(Acme.MultiTenant.EFDAL.EntityMappingConstants entity)
		{
			var item = GetMetaData(entity);
			if (item == null) return null;
			return item.GetTableName();
		}
		#endregion

		#region Interface Extras

		/// <summary>
		/// Reloads the context object from database
		/// </summary>
		public void ReloadItem(BaseEntity entity)
		{
			this.Entry(entity).Reload();
		}

		#endregion

		#region ObjectContext

		/// <summary>
		/// Determines the timeout of the database connection
		/// </summary>
		public int? CommandTimeout
		{
			get { return this.Database.GetCommandTimeout(); }
			set { this.Database.SetCommandTimeout(value); }
		}

		#endregion

	}
	#endregion

}

namespace Acme.MultiTenant.EFDAL.Entity
{
}
#pragma warning restore 612

